### ISSUE TITLE
TAP/TUN 代码是否能独立出来呢？

### ISSUE THREAD

**Issue by LuoZijun** [FlowerWrong/ip2socks#1]
你好，我正在尝试写一个 [tun2ssh](https://github.com/LuoZijun/rust-netproxy) 的项目，大概就是 转发 `TAP` 的数据包至 `TUN` 设备，然后把 `TUN` 设备中的 `TCP/UDP` 数据包 通过 `SSH` 通道放在远程服务器执行，并传回。

项目目标旨在提高易用性，减少配置。争取做到 一行命令解决所有问题:

```bash
tun2ssh --ssh_host "20.202.20.20" --ssh_name "root" --ssh_password "impasswd!"
tun2ssh --ssh_host "20.202.20.20" --ssh_name "root" --ssh_pri_key "~/.ssh/my_pri_key"
```

由于刚开始，对 `TAP/TUN` 这块还不太熟悉，也不懂 `C/C++` =_= ，项目目前是 采用 `rust` 写的。如果您能 把 `TAP/TUN` 这块代码拆分开来，提供 `C` 接口，那将会极大地加速 `tun2ssh` 项目的开发进度。

非常希望得到你的帮助。

**Comment by FlowerWrong** [comment]
类似 `ssh -N -D 1080 username@sshd_server` 吗？

**Comment by LuoZijun** [comment]
@FlowerWrong 是的。

SSH API: http://alexcrichton.com/ssh2-rs/ssh2/struct.Session.html#method.channel_direct_tcpip
Code: https://github.com/LuoZijun/rust-netproxy/blob/master/src/egress/ssh.rs#L56

只不过没有走 `socks` , 因为在 `tun` 里面直接转发至 SSH Channel.

**Comment by FlowerWrong** [comment]
可以看下这个是不是你想要的 [LaKabane/libtuntap](https://github.com/LaKabane/libtuntap) ？

**Comment by LuoZijun** [comment]
@FlowerWrong 没错，但是好像他们不维护了（目前支持还不完善）。

https://github.com/mmokhi/libUTunTap
我看了下他们的PR记录和讨论， [mmokhi](https://github.com/mmokhi) 提交了一个 对于 `freebsd` 平台的支持代码，但至今未被合并。

于是他开了一个新的项目 [mmokhi/libUTunTap](https://github.com/mmokhi/libUTunTap) ，代码结构看起来似乎更简洁了。

当然我还没有测试。计划这个周末看下。

**Comment by FlowerWrong** [comment]
`mmokhi/libUTunTap`似乎不支持darwin，没细看代码。

**Comment by LuoZijun** [comment]
@FlowerWrong 支持 `FreeBSD` 一般来说在 `XNU` 下面应该不太会有问题。具体周末看下。

苹果代码对应的 `FreeBSD` 代码:

https://github.com/apple/darwin-xnu/blob/master/bsd/net/bpf.c#L67

**Comment by LuoZijun** [comment]
@FlowerWrong 

找到了一个比较好的 `TUN` 库:

原始库: https://github.com/meh/rust-tun

修改完善版(未合并): https://github.com/realityone/akarin/tree/master/src/tun

https://github.com/LuoZijun/rust-netproxy/tree/master/taptun
