### ISSUE TITLE
编译不成功，可否提供mac上的可执行文件？

### ISSUE THREAD

**Issue by luckypoem** [FlowerWrong/ip2socks#10]
hi.
我在mac上，编译不成功，可否在https://github.com/FlowerWrong/ip2socks/releases 这里提供mac上的可执行文件？

**Comment by FlowerWrong** [comment]
报什么错？我好久没用这个了，我以前用过，支持mac和linux

**Comment by luckypoem** [comment]
hi.

git clone https://github.com/FlowerWrong/ip2socks ip2socks-by-FlowerWrong
cd ip2socks-by-FlowerWrong
rm -rf libyaml lwip lwip-contrib
git clone https://github.com/yaml/libyaml/
git clone https://github.com/FlowerWrong/lwip/
git clone https://github.com/FlowerWrong/lwip-contrib
mkdir build
cd build
cmake ..
make
显示：
...
[ 73%] Building C object CMakeFiles/ip2socks.dir/libyaml/src/api.c.o
/Users/brite/ip2socks-by-flowerwrong/libyaml/src/api.c:11:12: error: use of
      undeclared identifier 'YAML_VERSION_STRING'
    return YAML_VERSION_STRING;
           ^
/Users/brite/ip2socks-by-flowerwrong/libyaml/src/api.c:21:14: error: use of
      undeclared identifier 'YAML_VERSION_MAJOR'
    *major = YAML_VERSION_MAJOR;
             ^
/Users/brite/ip2socks-by-flowerwrong/libyaml/src/api.c:22:14: error: use of
      undeclared identifier 'YAML_VERSION_MINOR'
    *minor = YAML_VERSION_MINOR;
             ^
/Users/brite/ip2socks-by-flowerwrong/libyaml/src/api.c:23:14: error: use of
      undeclared identifier 'YAML_VERSION_PATCH'
    *patch = YAML_VERSION_PATCH;
             ^
4 errors generated.
make[2]: *** [CMakeFiles/ip2socks.dir/libyaml/src/api.c.o] Error 1
make[1]: *** [CMakeFiles/ip2socks.dir/all] Error 2
make: *** [all] Error 2
yudeMacBook-Air:build brite$

如何解决这个make遇到的错误？

**Comment by FlowerWrong** [comment]
pull sub module试下，master

**Comment by luckypoem** [comment]
怎么写命令

**Comment by FlowerWrong** [comment]
git submodule

**Comment by luckypoem** [comment]
hi,

yudeMacBook-Air:ip2socks-by-flowerwrong brite$ cmake .
-- The C compiler identification is AppleClang 8.1.0.8020042
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for include file inttypeas.h
-- Looking for include file inttypeas.h - not found
-- Looking for include file dlfcn.h
-- Looking for include file dlfcn.h - found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for include file poll.h
-- Looking for include file poll.h - found
-- Looking for include file port.h
-- Looking for include file port.h - not found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Looking for include file sys/epoll.h
-- Looking for include file sys/epoll.h - not found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - not found
-- Looking for include file sys/event.h
-- Looking for include file sys/event.h - found
-- Looking for include file sys/inotify.h
-- Looking for include file sys/inotify.h - not found
-- Looking for include file sys/select.h
-- Looking for include file sys/select.h - found
-- Looking for include file sys/signalfd.h
-- Looking for include file sys/signalfd.h - not found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for 15 include files assert.h, ..., time.h
-- Looking for 15 include files assert.h, ..., time.h - found
-- Looking for include file winsock.h
-- Looking for include file winsock.h - not found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for epoll_ctl
-- Looking for epoll_ctl - not found
-- Looking for eventfd
-- Looking for eventfd - not found
-- Looking for floor
-- Looking for floor - found
-- Looking for inotify_init
-- Looking for inotify_init - not found
-- Looking for kqueue
-- Looking for kqueue - found
-- Looking for nanosleep
-- Looking for nanosleep - found
-- Looking for poll
-- Looking for poll - found
-- Looking for port_create
-- Looking for port_create - not found
-- Looking for select
-- Looking for select - found
-- Looking for signalfd
-- Looking for signalfd - not found
-- Looking for pthread_create in rt
-- Looking for pthread_create in rt - not found
-- Configuring done
CMake Error at CMakeLists.txt:69 (add_executable):
  Cannot find source file:

    lwip/src/core/init.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:69 (add_executable):
  No SOURCES given to target: ip2socks


-- Build files have been written to: /Users/brite/ip2socks-by-flowerwrong
yudeMacBook-Air:ip2socks-by-flowerwrong brite$ ls
CMakeCache.txt	README.md	cmake		lwip		src
CMakeFiles	Rakefile	libev		lwip-contrib
CMakeLists.txt	Vagrantfile	libyaml		scripts
yudeMacBook-Air:ip2socks-by-flowerwrong brite$

还是搞不定，兄台不妨亲自试试？

**Comment by FlowerWrong** [comment]
```
git clone git@github.com:FlowerWrong/ip2socks.git
git submodule init
git submodule update

cmake .
make
```
it's ok.

**Comment by luckypoem** [comment]
hello.

yudeMacBook-Air:~ brite$ git clone https://github.com/FlowerWrong/ip2socks ip2socks-by-FlowerWrong
Cloning into 'ip2socks-by-FlowerWrong'...
remote: Enumerating objects: 1554, done.
remote: Total 1554 (delta 0), reused 0 (delta 0), pack-reused 1554
Receiving objects: 100% (1554/1554), 4.72 MiB | 357.00 KiB/s, done.
Resolving deltas: 100% (951/951), done.
Checking connectivity... done.
yudeMacBook-Air:~ brite$ cd ip2socks-by-FlowerWrong
yudeMacBook-Air:ip2socks-by-FlowerWrong brite$ git submodule update --init --recursive
Submodule 'libyaml' (git@github.com:yaml/libyaml.git) registered for path 'libyaml'
Submodule 'lwip' (git@github.com:FlowerWrong/lwip.git) registered for path 'lwip'
Submodule 'lwip-contrib' (git@github.com:FlowerWrong/lwip-contrib.git) registered for path 'lwip-contrib'
Submodule 'scripts/china_ip_list' (git@github.com:17mon/china_ip_list.git) registered for path 'scripts/china_ip_list'
Submodule 'scripts/dnsmasq-china-list' (git@github.com:felixonmars/dnsmasq-china-list.git) registered for path 'scripts/dnsmasq-china-list'
Cloning into 'libyaml'...
Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:yaml/libyaml.git' into submodule path 'libyaml' failed
yudeMacBook-Air:ip2socks-by-FlowerWrong brite$ git submodule init
yudeMacBook-Air:ip2socks-by-FlowerWrong brite$ git submodule update
Cloning into 'libyaml'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:yaml/libyaml.git' into submodule path 'libyaml' failed
yudeMacBook-Air:ip2socks-by-FlowerWrong brite$

libyaml包克隆不下来。怪事，https://github.com/yaml/libyaml是存在的啊

**Comment by FlowerWrong** [comment]
use ssh protocol `git clone git@github.com:FlowerWrong/ip2socks.git`

**Comment by luckypoem** [comment]
hi.

yudeMacBook-Air:~ brite$ git clone git@github.com:FlowerWrong/ip2socks.git
Cloning into 'ip2socks'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
yudeMacBook-Air:~ brite$

怎么解决？很奇怪。挂了vpn后，还是上面的提示

**Comment by FlowerWrong** [comment]
看一下gitbook吧，https://help.github.com/cn/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

**Comment by luckypoem** [comment]
hi,
我添加了ssh public key到我的github a/c,这次：
git clone git@github.com:FlowerWrong/ip2socks.git 正常
git submodule update --init --recursive 正常
mkdir build
cd buid
cmake .. (正常，生成了Makefile)
make
显示：
...
[ 72%] Building C object CMakeFiles/ip2socks.dir/libev/ev.c.o
/Users/yuming/ip2socks/libev/ev.c:45:12: fatal error: 'config.h' file not found
#  include "config.h"
           ^
1 error generated.
make[2]: *** [CMakeFiles/ip2socks.dir/libev/ev.c.o] Error 1
make[1]: *** [CMakeFiles/ip2socks.dir/all] Error 2
make: *** [all] Error 2
yudeMacBook-Air:build brite$

怎么解决？

**Comment by luckypoem** [comment]
哦，明白了。只能像你说的那样做：
cmake .
make

**Comment by luckypoem** [comment]
但是配置文件怎么写？
yudeMacBook-Air:ip2socks brite$ ./ip2socks -h
options:
-d --debug
-h --help
-c --config
yudeMacBook-Air:ip2socks brite$

**Comment by luckypoem** [comment]
哦，看到配置文件了：
https://github.com/FlowerWrong/ip2socks/blob/master/scripts/config.darwin.example.yml

不过，
yudeMacBook-Air:ip2socks brite$ sudo ./ip2socks -c config.darwin.yml
Lwip netstack host 10.0.0.2 mask 255.255.255.0 gateway 10.0.0.1
connect[AF_SYS_CONTROL]tun name is utun1
exec setup shell sh ./scripts/darwin_setup_utun.sh 10.0.0.1
origin gateway is '192.168.1.1'
batch add chnroutes
add net 128.0.0.0: gateway 10.0.0.1
add net 0.0.0.0: gateway 10.0.0.1
add host 114.114.114.114: gateway 192.168.1.1
add host 223.5.5.5: gateway 192.168.1.1
add host 47.52.95.27: gateway 192.168.1.1
Ip2socks started!
recv VERSION and METHODS error
socks5 auth error
recv VERSION and METHODS error
socks5 auth error
recv VERSION and METHODS error
socks5 auth error
recv VERSION and METHODS error
socks5 auth error
recv VERSION and METHODS error
socks5 auth error

如何去掉socks5 auth error？修改什么地方？

**Comment by luckypoem** [comment]
哦，这个提示“socks5 auth error”无关紧要，

**Comment by FlowerWrong** [comment]
配置文件你需要自己修改一下，47.52.95.27是我的地址

**Comment by luckypoem** [comment]
嗯，
 nano scripts/darwin_setup_utun.sh
把47.52.95.27改为我的vps ip
