### ISSUE TITLE
Running make on OSX 10.13.3 and Xcode v9.2 (9C40b)

### ISSUE THREAD

**Issue by TomHoenderdos** [FlowerWrong/ip2socks#3]
[  1%] Building C object CMakeFiles/ip2socks.dir/src/dns/dns_parser.c.o
In file included from /Users/tom/Projects/ip2socks/src/dns/dns_parser.c:1:
/Users/tom/Projects/ip2socks/src/dns/dns_parser.h:1:10: fatal error: 'unittypes.h' file not found
#include <unittypes.h>
         ^~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/ip2socks.dir/src/dns/dns_parser.c.o] Error 1
make[1]: *** [CMakeFiles/ip2socks.dir/all] Error 2
make: *** [all] Error 2

Any tips to solve this?

**Comment by Contextualist** [comment]
Changing the following line to `#include <sys/types.h>` fixes the issue for me
https://github.com/FlowerWrong/ip2socks/blob/03fc2c44ec615a8380da38a80ec2dd5bdb2d6742/src/dns/dns_parser.h#L1
But I'm not sure if it is compatible with other platform.

**Comment by FlowerWrong** [comment]
Thanks @Contextualist , it worked on many bsd plateform. [is-u-char-a-standard](https://stackoverflow.com/questions/1918934/is-u-char-a-standard)
