### ISSUE TITLE
作者你好，请教你个问题

### ISSUE THREAD

**Issue by android0276** [FlowerWrong/ip2socks#5]
1. 我想问下ip2socks 和 tun2socks的区别是啥，两个都处理的是IP流对吗，区别难道是ip2sock支持tun和tap两种方式。
2. git clone git@github.com:FlowerWrong/ip2socks.git --recursive 提示没有权限，麻烦授予下权限。
3. 这个批量添加路由是什么原理，这里面添加批量的这个route的源码有吗。

**Comment by FlowerWrong** [comment]
这个我还真不知道原因，我这里试试是可以的。我并没有设置权限之类的。你可以分别点开里面依赖的几个仓库看看。

**Comment by android0276** [comment]
好

**Comment by android0276** [comment]
ip2socks和tun2socks   目前你推荐使用哪个好一点，我打算把你这个跑起来试试

**Comment by FlowerWrong** [comment]
看你熟悉c还是go，使用的话，tun2socks会好点。fake mode类似surge for mac的全局模式。

**Comment by android0276** [comment]
你好，亲麻烦看下，我这个运行日志为啥这么多失败
![image](https://user-images.githubusercontent.com/8524130/49492622-05be3580-f894-11e8-8239-e94f9fe40f43.png)

**Comment by android0276** [comment]
1. 就是说如果添加例外的话直接走HTTP代理了, 不会走到TUN这一层, 为啥日志后面弄四个????
2. 再问一个问题，为啥有些DNS解析失败，比如http://im.ding.talk，如上图
3. 这个包编译出来有19M，好大...，能精简吗
4. 我的代理服务器是通过域名访问的话，是不是要添加这个域名到例外，让这个域名不返回Fake IP
5. 如果有些软件直接访问的是TP，这时候Fake mode是不是就无能为力了。

**Comment by FlowerWrong** [comment]
1. 是为了让我丰富自己的配置，出现这个我就加到配置列表里面，避免dns请求和geoip的解析等等。
2. 有些dns会失败，例如超时什么的，我遇到的有用腾讯dns服务器去解析阿里域名，类似的。偶尔出现。
3. 没试过，我想应该减不到哪里去，毕竟依赖go
4. 是的，如果是ip会自动添加，域名还真没试过
5. TP是什么？

**Comment by android0276** [comment]
打错了，是ip

**Comment by FlowerWrong** [comment]
5. 是的，但是内置了`route`功能，[见](https://github.com/FlowerWrong/tun2socks/blob/master/config.example.ini#L38-L52)，添加到配置或者自己脚本批量添加也可以。
